In [1]:
import pydecode
import numpy as np
import matplotlib.pyplot as plt

In [2]:
t = 5 #time
pStorage, pManufacturing = 0, 1
operations = np.array([pStorage, pManufacturing])
offsets = np.array([[1,0], [0,1], [1,1]])
op_names = np.array(["Lagerung", "Produktion"])

def grid(m, n, o=None):
    if o is None:
        return np.arange(m * n).reshape((m, n))
    else:
        return np.arange(m * n * o).reshape((m, n, o))
grid(t,t)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [3]:
def ungrid(items, shape):
    return np.array(np.unravel_index(items, shape)).T
ungrid([1, 2, 3, 4], (t,t))

array([[0, 1],
       [0, 2],
       [0, 3],
       [0, 4]])

In [4]:
def edit_distance(m, n):

    # Create a grid for the items and labels.
    item_grid = grid(m, n)
    op_grid = grid(m, n, len(operations))
    c = pydecode.ChartBuilder(item_grid)

    # Construct the base cases.
    c.init(item_grid[0, 0])
    c.init(item_grid[0, 1:])
    c.init(item_grid[1:, 0])

    # Construct the recursion.
    for i in range(1, m):
        for j in range(1, n):
            c.set(item_grid[i, j],
                  [[item_grid[i-1, j]],
                   [item_grid[i, j-1]],
                   [item_grid[i-1, j-1]]],
                  [op_grid[i-1, j, kDelete],
                   op_grid[i, j-1, kInsert],
                   op_grid[i-1, j-1, kMatch]])
    return c.finish()

In [5]:
graph = edit_distance(3, 3)

NameError: global name 'kDelete' is not defined

In [6]:
def make_scores(string1, string2):
    m, n = len(string1), len(string2)
    scores = np.zeros((m, n, 3))
    for i, s in enumerate(string1):
        for j, t in enumerate(string2):
            scores[i, j, kMatch] = 1.0 if s == t \
                                       else -1e8
    return scores
string1, string2 = "aab", "aac"
scores = make_scores(string1, string2)
weights = pydecode.transform(graph, scores)

NameError: global name 'kMatch' is not defined

In [ ]:
path = pydecode.best_path(graph, weights)
ungrid([edge.label for edge in path.edges], (3,3, 3))
ungrid([node.label for node in path.nodes], (3,3))

In [7]:
array([[0, 0],
       [1, 1],
       [2, 2]])

NameError: name 'array' is not defined