In [ ]:
__version__ = '0.3'
__author__  = "Robert Matern (r.matern@stud.uni-hannover.de)"
__date__    = ''
__url__     = ''
__copyright__ = "(C) 2015 Robert Matern"

In [1]:
# import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
%run Parameter.ipynb

#%run Data02.ipynb

In [2]:
# Beispieldaten
# Produkte
products = Product(2)

# Ressourcen
resources = Resource(4)

#Kapazität
capacities = Capacity(resources)
capacities[1] = 2
capacities[2] = 1
capacities[3] = 3
capacities[4] = 4
#capacities[5] = 5
#capacities[6] = 6
#capacities[7] = 7
#capacities[8] = 8
#capacities[9] = 9
#capacities[10] = 10

# Ressourcenverbrauch
consumtions = Consumption(products, resources)
consumtions[1] = [0,1,0,1,0]#,1,1,0,1,1,1]
consumtions[2] = [0,0,1,0,1]#,1,0,0,1,1,0]

# Erträge
revenues = Revenue(products)
revenues[1] = 100
revenues[2] = 200

# Buchungshorizont
times = Time(4)

# Wahrscheinlichkeiten
probs = Prob(products, times)
probs[1] = [0.5, 0.3, 0.5, 0.5, 0]
probs[2] = [0.1, 0.1, 0.1, 0.1, 0]

# Gegenwahrscheinlichkeiten
against_probs = Against_Prob(probs)

# Systemzustände
#conditions = Condition(capacities, resources, times)
#conditions

In [45]:
def Condition(capacities, resources, times):
    '''Berechnung der möglichen Systemzustände eines Netzwerks
    mit c Kapazitäten, r Ressourcen und t Perioden.'''
    # Ermittlung der Rechenzeit
    import datetime
    a = datetime.datetime.now()
    
    # Erstellung eines Multiprozesses
    #import multiprocessing as mp
    #pool = mp.Pool(processes=4)
    
    
    from itertools import product
    array = [range(i) for i in capacities[1:]+1]
    scope = (np.asarray(subset) for subset in product(*array))
    conditions = [
        [subset.copy(), j]
        for subset in scope
        for j in times
    ]
    np.savetxt('test.txt', conditions, delimiter=',', fmt="%s")
    

    
    b = datetime.datetime.now()
    print (b-a)
    return conditions

Condition(capacities, resources, times)

0:00:00.477398


[[array([0, 0, 0, 0]), 4],
 [array([0, 0, 0, 0]), 3],
 [array([0, 0, 0, 0]), 2],
 [array([0, 0, 0, 0]), 1],
 [array([0, 0, 0, 0]), 0],
 [array([0, 0, 0, 1]), 4],
 [array([0, 0, 0, 1]), 3],
 [array([0, 0, 0, 1]), 2],
 [array([0, 0, 0, 1]), 1],
 [array([0, 0, 0, 1]), 0],
 [array([0, 0, 0, 2]), 4],
 [array([0, 0, 0, 2]), 3],
 [array([0, 0, 0, 2]), 2],
 [array([0, 0, 0, 2]), 1],
 [array([0, 0, 0, 2]), 0],
 [array([0, 0, 0, 3]), 4],
 [array([0, 0, 0, 3]), 3],
 [array([0, 0, 0, 3]), 2],
 [array([0, 0, 0, 3]), 1],
 [array([0, 0, 0, 3]), 0],
 [array([0, 0, 0, 4]), 4],
 [array([0, 0, 0, 4]), 3],
 [array([0, 0, 0, 4]), 2],
 [array([0, 0, 0, 4]), 1],
 [array([0, 0, 0, 4]), 0],
 [array([0, 0, 1, 0]), 4],
 [array([0, 0, 1, 0]), 3],
 [array([0, 0, 1, 0]), 2],
 [array([0, 0, 1, 0]), 1],
 [array([0, 0, 1, 0]), 0],
 [array([0, 0, 1, 1]), 4],
 [array([0, 0, 1, 1]), 3],
 [array([0, 0, 1, 1]), 2],
 [array([0, 0, 1, 1]), 1],
 [array([0, 0, 1, 1]), 0],
 [array([0, 0, 1, 2]), 4],
 [array([0, 0, 1, 2]), 3],
 

In [52]:
a = [range(i) for i in capacities[1:]+1]
for i in a:
    np.append(a, np.array(i))

def cartesian(arrays, out=None):
    """
    Generate a cartesian product of input arrays.

    Parameters
    ----------
    arrays : list of array-like
        1-D arrays to form the cartesian product of.
    out : ndarray
        Array to place the cartesian product in.

    Returns
    -------
    out : ndarray
        2-D array of shape (M, len(arrays)) containing cartesian products
        formed of input arrays.

    Examples
    --------
    >>> cartesian(([1, 2, 3], [4, 5], [6, 7]))
    array([[1, 4, 6],
           [1, 4, 7],
           [1, 5, 6],
           [1, 5, 7],
           [2, 4, 6],
           [2, 4, 7],
           [2, 5, 6],
           [2, 5, 7],
           [3, 4, 6],
           [3, 4, 7],
           [3, 5, 6],
           [3, 5, 7]])

    """

    arrays = [np.asarray(x) for x in arrays]
    dtype = arrays[0].dtype

    n = np.prod([x.size for x in arrays])
    if out is None:
        out = np.zeros([n, len(arrays)], dtype=dtype)

    m = n / arrays[0].size
    out[:,0] = np.repeat(arrays[0], m)
    if arrays[1:]:
        cartesian(arrays[1:], out=out[0:m,1:])
        for j in xrange(1, arrays[0].size):
            out[j*m:(j+1)*m,1:] = out[0:m,1:]
    return out

cartesian(a)

array([[0, 0, 0, 0],
       [0, 0, 0, 1],
       [0, 0, 0, 2],
       [0, 0, 0, 3],
       [0, 0, 0, 4],
       [0, 0, 1, 0],
       [0, 0, 1, 1],
       [0, 0, 1, 2],
       [0, 0, 1, 3],
       [0, 0, 1, 4],
       [0, 0, 2, 0],
       [0, 0, 2, 1],
       [0, 0, 2, 2],
       [0, 0, 2, 3],
       [0, 0, 2, 4],
       [0, 0, 3, 0],
       [0, 0, 3, 1],
       [0, 0, 3, 2],
       [0, 0, 3, 3],
       [0, 0, 3, 4],
       [0, 1, 0, 0],
       [0, 1, 0, 1],
       [0, 1, 0, 2],
       [0, 1, 0, 3],
       [0, 1, 0, 4],
       [0, 1, 1, 0],
       [0, 1, 1, 1],
       [0, 1, 1, 2],
       [0, 1, 1, 3],
       [0, 1, 1, 4],
       [0, 1, 2, 0],
       [0, 1, 2, 1],
       [0, 1, 2, 2],
       [0, 1, 2, 3],
       [0, 1, 2, 4],
       [0, 1, 3, 0],
       [0, 1, 3, 1],
       [0, 1, 3, 2],
       [0, 1, 3, 3],
       [0, 1, 3, 4],
       [1, 0, 0, 0],
       [1, 0, 0, 1],
       [1, 0, 0, 2],
       [1, 0, 0, 3],
       [1, 0, 0, 4],
       [1, 0, 1, 0],
       [1, 0, 1, 1],
       [1, 0,

In [32]:
print capacities
print resources
print times

[0 2 1 3 4]
[0 1 2 3 4]
[4 3 2 1 0]


In [ ]:
def Condition(capacities, resources, times):
    '''Berechnung der möglichen Systemzustände eines Netzwerks
    mit c Kapazitäten, r Ressourcen und t Perioden.'''
    # Ermittlung der Rechenzeit
    import datetime
    a = datetime.datetime.now()
    
    from itertools import product
    scope = [] 
    conditions = [] 
    array = []
    for h in resources[1:]:
        array = array + [range(capacities[h]+1)]
        print array
    for subset in product(*array):
        scope = scope + [subset]
    for subset in scope:    
        for t in range(len(times)):
            conditions = conditions + [[np.asarray(subset), times[t]]]
    np.savetxt('test.txt', conditions, delimiter=',', fmt="%s")
    
    b = datetime.datetime.now()
    print (b-a)
    return conditions

    
# Erstellung eines Multiprozesses
import multiprocessing as mp
pool = mp.Pool(processes=4)
results = [pool.apply(Condition, args=(capacities, resources, times))]
test = map(list, results)
test

#Dynamisches Programm

Die normale Modellformulierung des Auftragsannahmeproblems im Revenue Management von Instandhaltungsprozessen:

$$V(\textbf{c}, t) = \sum_{j \in \mathcal{J}}p_{j}(t)\max[V(\textbf{c}, t-1), r_{j} + V(\textbf{c}-\textbf{a}_j, t-1)] + p_{0}(t)V(\textbf{c}, t-1) $$

$$= V(\textbf{c}, t-1) + \sum_{j \in \mathcal{J}}p_{j}(t) \max[r_j - V(\textbf{c}, t-1) + V(\textbf{c}-\textbf{a}_j, t-1), 0]$$

In [ ]:
def Condition(capacities, resources, times):
    '''Berechnung der möglichen Systemzustände eines Netzwerks
    mit c Kapazitäten, r Ressourcen und t Perioden.'''
    import datetime
    a = datetime.datetime.now()
    from itertools import product
    conditions = [] 
    conditions2 = [] 
    array = []
    for h in resources[1:]:
        array = array + [range(capacities[h]+1)]
    for subset in product(*array):
        conditions = conditions + [np.asarray(subset)]
    for subset in conditions:    
        for t in range(len(times)):
            conditions2 = conditions2 + [[subset, times[t]]]
    np.savetxt('test.txt', conditions, delimiter=',', fmt="%s")
    b = datetime.datetime.now()
    print (b-a)
    return conditions2

Condition(capacities, resources, times)

In [ ]:
%run DynamicProgramm.ipynb

In [ ]:
DP(solutions, conditions, products, resources, capacities, consumtions, times)

In [ ]:
solutions = {}

def DP(solutions, conditions, products, resources, capacities, consumtions, times):
    '''Berechnung des maximal möglichen Erwartungswertes eines Auftragsannahmeproblems.'''
    
    # Leere Integer für den Erwartungswert
    value = 0
    
    # Über eine Schleife und einer If-Bedingung wird der aktuelle Systemzustand ermittelt.
    for g in range(len(conditions)):
        if np.array_equal(np.asarray(conditions[g][0]), capacities[1:]) and np.asarray(conditions[g][1]) == times[0]:
            
            # Memofunktion: Das DP wird nur fortgeführt, sofern es nicht schon berechnet wurde.
            if g not in solutions:
                
                # Sofern es sich nicht um einen Endknoten des Entscheidungsbaums handelt, werden folgende Schritte eingeleitet:
                if times[0]!=0:
                    # Das DP(t-1) ohne Akeptanz wird gelöst und im Wert "value2" gespeichert.
                    value2 = (DP(solutions, conditions, products, resources, capacities, consumtions, times[1:]))
                    # Für das DP(t-1) mit Akzeptanz wird ein Numpy-Array in der Länge der Anzahl an Produkten erstellt.
                    value3 = np.zeros(shape=(len(products[1:])), dtype=np.float16)
                    # For-Schleife über alle Produkte, sofern die Kapazitäten keinen negativen Werte annehmen.
                    for j in products[1:]:
                        if np.all((capacities-consumtions[j]) >= 0):
                            # Initialisierung des DP(t-1) mit Akeptanz jeweils für ein Produkt j.
                            value3[j-1] = probs[j][0]*max(revenues[j]-DP(solutions, conditions, products, resources, capacities, consumtions, times[1:])+DP(solutions, conditions, products, resources, capacities-consumtions[j], consumtions, times[1:]),0)
                        else:    
                            # Erwartungswert für ein Produkt j enspricht der Grenzbedingung V(c,t)=-∞, falls n[j] < 0.
                            value3[j-1] = 0
                    # Summierung des DP(t-1) ohne Akzeptanz sowie den Numpy-Array DP(t-1) mit Akzeptanz.
                    value = value2 + np.sum(value3)
                    # Für den aktuellen Systemzustand wird der Ertragswert in das Dict "solutions" gespeichert.
                    solutions[g] = [[conditions[g], value]]

                # Sofern es sich um einen Endknoten des Entscheidungsbaums handelt, werden folgende Schritte eingeleitet:
                else:
                    # Erwartungswert enspricht der Grenzbedingung V(c,0)=0, für n >= 0.
                    value = 0.0
                    # Ein Endzustand wird mit einem Erwartungswert 0 in das Dict "solutions" gespeichert.
                    solutions[g] = [[conditions[g], value]]
                    return value        
            
            # Memofunktion: Sofern das Ergebnis breits berechnet wurde, wird der Wert aus dem Dict "solutions" verwendet.
            else:
                value = solutions[g][0][1]
    
    return value

In [ ]:
conditions = [[[capacities[1:]], times[0]]]
def Condition(conditions, capacities, resources, consumtions, times):
    if times[0] != 0:
        for j in products:
            check = capacities-consumtions[j]
            if np.all((check) >= 0):
                new_capacities = [capacities[1:]-consumtions[j][1:]]
                condition = [[new_capacities, times[1]]]
                if condition not in conditions:
                    conditions += condition
                    Condition(conditions, capacities-consumtions[j], resources, consumtions, times[1:])
    return conditions

conditions = Condition(conditions, capacities, resources, consumtions, times)
len(conditions)

In [ ]:
from functools import wraps
def Memo(func):
    '''A Memoizing Decorator. The idea of memoized function is that it caches its return values. If you call it a
    second time with the same parameters, it will simply return the cached value. You can certainly (allerdings) 
    put this sort of caching logic inside your function, but memo function is a more reusable (Mehrweg-) solution.
    '''
    cache = {}                           # Stored subproblem solutions
    @wraps(func)                         # Make wrap look like func
    def wrap(*args):                     # The memoized wrapper
        if args not in cache:            # Not already computed?
            cache[args] = func(*args)    # Compute & cache the solution
        return cache[args]               # Return the cached solution
    return wrap  

In [ ]:
solutions

## 0/1 Knapsack lt. http://rosettacode.org/wiki/Knapsack_problem/0-1#Python

###Recursive dynamic programming algorithm

In [ ]:
def total_value(items, max_weight):
    return  sum([x[2] for x in items]) if sum([x[1] for x in items]) < max_weight else 0
 
cache = {}
def solve(items, max_weight):
    if not items:
        return ()
    if (items,max_weight) not in cache:
        head = items[0]
        tail = items[1:]
        include = (head,) + solve(tail, max_weight - head[1])
        dont_include = solve(tail, max_weight)
        if total_value(include, max_weight) > total_value(dont_include, max_weight):
            answer = include
        else:
            answer = dont_include
        cache[(items,max_weight)] = answer
    return cache[(items,max_weight)]
 
items = (
    ("map", 9, 150), ("compass", 13, 35), ("water", 153, 200), ("sandwich", 50, 160),
    ("glucose", 15, 60), ("tin", 68, 45), ("banana", 27, 60), ("apple", 39, 40),
    ("cheese", 23, 30), ("beer", 52, 10), ("suntan cream", 11, 70), ("camera", 32, 30),
    ("t-shirt", 24, 15), ("trousers", 48, 10), ("umbrella", 73, 40),
    ("waterproof trousers", 42, 70), ("waterproof overclothes", 43, 75),
    ("note-case", 22, 80), ("sunglasses", 7, 20), ("towel", 18, 12),
    ("socks", 4, 50), ("book", 30, 10),
    )
max_weight = 400
 
solution = solve(items, max_weight)
print "items:"
for x in solution:
    print x[0]
print "value:", total_value(solution, max_weight)
print "weight:", sum([x[1] for x in solution])

###Dynamic programming solution

In [ ]:
try:
    xrange
except:
    xrange = range
 
def totalvalue(comb):
    ' Totalise a particular combination of items'
    totwt = totval = 0
    for item, wt, val in comb:
        totwt  += wt
        totval += val
    return (totval, -totwt) if totwt <= 400 else (0, 0)
 
items = (
    ("map", 9, 150), ("compass", 13, 35), ("water", 153, 200), ("sandwich", 50, 160),
    ("glucose", 15, 60), ("tin", 68, 45), ("banana", 27, 60), ("apple", 39, 40),
    ("cheese", 23, 30), ("beer", 52, 10), ("suntan cream", 11, 70), ("camera", 32, 30),
    ("t-shirt", 24, 15), ("trousers", 48, 10), ("umbrella", 73, 40),
    ("waterproof trousers", 42, 70), ("waterproof overclothes", 43, 75),
    ("note-case", 22, 80), ("sunglasses", 7, 20), ("towel", 18, 12),
    ("socks", 4, 50), ("book", 30, 10),
    )
 
def knapsack01_dp(items, limit):
    table = [[0 for w in range(limit + 1)] for j in xrange(len(items) + 1)]
 
    for j in xrange(1, len(items) + 1):
        item, wt, val = items[j-1]
        for w in xrange(1, limit + 1):
            if wt > w:
                table[j][w] = table[j-1][w]
            else:
                table[j][w] = max(table[j-1][w],
                                  table[j-1][w-wt] + val)
 
    result = []
    w = limit
    for j in range(len(items), 0, -1):
        was_added = table[j][w] != table[j-1][w]
 
        if was_added:
            item, wt, val = items[j-1]
            result.append(items[j-1])
            w -= wt
 
    return result
 
 
bagged = knapsack01_dp(items, 400)
print("Bagged the following items\n  " +
      '\n  '.join(sorted(item for item,_,_ in bagged)))
val, wt = totalvalue(bagged)
print("for a total value of %i and a total weight of %i" % (val, -wt))

## Versuche

In [ ]:
#@Memo
def Value(Product, Resource, Capacity, Consumption, Revenue, Time, Prob, Against_Prob):
    #accept = np.zeros(len(j)+1)                               # Funktioniert
    #reject = np.zeros(len(j)+1)                               # Funktioniert
    accept = []
    reject = []
    for i in Product:                                   # 0 -> 1 ; 1 -> 2 ; usw.
        for t in range(len(Time)):
            accept.append(Prob[i+1][t] * ( Revenue[i+1] + Value(Product, Resource, Capacity-Consumption[i], 
                                                                Consumption, Revenue, Time[t+1:], Prob, Against_Prob) ))
            reject.append(Prob[i+1][t] * Value(j==i+1, c[i], a[i], r[i], t-1, p[i]))
        if reject[i] > accept[i]: #Was mit größer gleich?
            return reject
        else:
            return accept

Value(products, resources, capacities, consumtions, revenues, times, probs, against_probs)

In [ ]:
#kReject, kAccept = 0, 1
#operations = np.array([kReject, kAccept])
#offsets = np.array([[1,0], [0,1], [1,1]]) 
#op_names = np.array(["Reject",  "Accept"])

##Memofunction

##Networkx

In [ ]:
import networkx as nx

In [ ]:
G=nx.Graph()
G.add_node("spam")
G.add_edge(1,2)
print(G.nodes())
[1, 2, 'spam']
print(G.edges())
[(1, 2)]

##PyDecode

In [ ]:
import pydecode
import pydecode.test.utils

In [ ]:
def test_hypergraph():
    """
    Create a test hypergraph. (C) PyDecode
    """
    enc = np.arange(6) # [0 1 2 3 4 5]

    c = pydecode.ChartBuilder(enc, np.arange(10)) # <pydecode._pydecode.ChartBuilder object at 0x10a06d550>

    c.init(enc[:4])

    c.set_t(enc[4], enc[0:2], enc[1:3], labels=np.arange(2))
    c.set_t(enc[5], np.repeat(enc[4], 1), enc[[3]], labels=np.array([2]))
    
    dp = c.finish() # <pydecode._pydecode.Hypergraph object at 0x10a164d60>

    # for edge in hypergraph.edges:
    #     assert edge.label in ["0", "1", "2", "3", "4"]
    return dp

In [ ]:
graph = test_hypergraph()
weights = np.random.randint(10, size=(len(graph.edges)))
print weights
pydecode.draw(graph, weights)

In [ ]:
times
chart = pydecode.ChartBuilder(times)
chart.init(times[1:len(times)])
chart.set(times[0],
          [[times[1]], [times[2]], [times[3]], [times[4]]],
          labels=[1,2,3,4])
pydecode.draw(chart.finish(), labels=True)

In [ ]:
def simple_hypergraph():
    """
    Create a simple hypergraph.
    """
    enc = np.arange(7)                                          # array([0, 1, 2, 3, 4, 5])
    c = pydecode.ChartBuilder(enc, np.arange(10))               # <pydecode._pydecode.ChartBuilder at 0x105604150>

    c.init(enc[:4])                                             # None
    
    c.set_t(enc[4], enc[0:2], enc[1:3], labels=np.arange(2))    # None
    
    c.set_t(enc[5], np.repeat(enc[4], 1), enc[[3]], labels=np.array([2])) # None
    
    c.set_t(enc[6], np.repeat(enc[5], 1), enc[[4]], labels=np.array([3])) # None
    
    dp = c.finish()                                             # <pydecode._pydecode.Hypergraph object at 0x1079d2aa0>
    # for edge in hypergraph.edges:
    #     assert edge.label in ["0", "1", "2", "3", "4"]
    return dp

hypergraph = simple_hypergraph()

for vertex in hypergraph.vertices:
    print vertex.id, vertex.is_terminal
    for edge in vertex.edges:
        print "\t", edge.id, edge.label

In [ ]:
inside = pydecode.inside(graph, np.array(weights, dtype=np.double),
                weight_type=pydecode.LogViterbi)
pydecode.draw(graph, weights, inside)

In [ ]:
path = pydecode.best_path(graph, weights * 1.)
pydecode.draw(graph, weights, inside, paths=[path])

In [ ]:
items = np.arange(100)
#print items
chart = pydecode.ChartBuilder(items)   

i=1
n=0
m=2

chart.init(items[0:m]) # Die Quadrate werden erstellt

#for i in range(m):

chart.set_t(items[10],                  # 1 ist verbunden...
            items[n:m],                # ...mit den Ovalen.
            labels=np.arange(m)
           )       # Bezeichnung der Ovale
chart.set_t(items[10],                  # 1 ist verbunden...
            items[n:m],                # ...mit den Ovalen.
            labels=np.arange(m)
           )       # Bezeichnung der Ovale
pydecode.draw(chart.finish(), labels=True)